services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '${DB_PORT}:5432'

  taak-backend:
    image: 'taak:0.0.1-SNAPSHOT'
    depends_on:
      - postgres
    environment:
    #これはapplication.propertiesよりも優先される
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
      - 'JWT_SECRET=${JWT_SECRET}'
    ports:
      - '${SPRING_APPLICATION_PORT}:8080'
