name: Task
description: エンジニアの開発タスク
title: "[Task]: "
type: Task
body:
  - type: textarea
    id: abstract
    attributes:
      label: 概要
      description: タスクの概要
      placeholder: |
        タスク作成APIの実装
    validations:
      required: true
  - type: textarea
    id: specification
    attributes:
      label: 仕様
      description: 実装する機能の仕様
      placeholder: |
        - method: POST
        - url: /api/tasks
        - request body:
          ```json
          {
            "title": "タスクのタイトル",
            "description": "タスクの詳細"
          }
          ```
        - response:
          ```json
          {
            "id": 1,
            "title": "タスクのタイトル",
            "description": "タスクの詳細",
            "created_at": "2023-10-01T00:00:00Z"
          }
          ```
    validations:
      required: true
  - type: textarea
    id: dependency
    attributes:
      label: 依存関係
      description: このタスクに取り組む前に終わらせておくべきタスク
      placeholder: |
        - #[issue番号]
  - type: textarea
    id: reference
    attributes:
      label: 参考資料
      description: タスクに関連する資料があればリンクを貼る
      placeholder: |
        - [README.md](https://github.com/LY-HackU-2025-team8/taaks/blob/main/README.md)
