/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as RegisterImport } from './app/routes/register'
import { Route as AuthImport } from './app/routes/_auth'
import { Route as AppImport } from './app/routes/_app'
import { Route as IndexImport } from './app/routes/index'
import { Route as RegisterNicknameImport } from './app/routes/register/nickname'
import { Route as RegisterHairImport } from './app/routes/register/hair'
import { Route as RegisterColorImport } from './app/routes/register/color'
import { Route as RegisterClothesImport } from './app/routes/register/clothes'
import { Route as RegisterBuddyNameImport } from './app/routes/register/buddy-name'
import { Route as AuthLoginImport } from './app/routes/_auth/login'
import { Route as AppTodoImport } from './app/routes/_app/todo'
import { Route as AppDiaryImport } from './app/routes/_app/diary'
import { Route as AppDashboardImport } from './app/routes/_app/dashboard'
import { Route as AppBuddyImport } from './app/routes/_app/buddy'
import { Route as AppAccountImport } from './app/routes/_app/account'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterNicknameRoute = RegisterNicknameImport.update({
  id: '/nickname',
  path: '/nickname',
  getParentRoute: () => RegisterRoute,
} as any)

const RegisterHairRoute = RegisterHairImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => RegisterRoute,
} as any)

const RegisterColorRoute = RegisterColorImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => RegisterRoute,
} as any)

const RegisterClothesRoute = RegisterClothesImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => RegisterRoute,
} as any)

const RegisterBuddyNameRoute = RegisterBuddyNameImport.update({
  id: '/buddy-name',
  path: '/buddy-name',
  getParentRoute: () => RegisterRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppTodoRoute = AppTodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppRoute,
} as any)

const AppDiaryRoute = AppDiaryImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppBuddyRoute = AppBuddyImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => AppRoute,
} as any)

const AppAccountRoute = AppAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountImport
      parentRoute: typeof AppImport
    }
    '/_app/buddy': {
      id: '/_app/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof AppBuddyImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryImport
      parentRoute: typeof AppImport
    }
    '/_app/todo': {
      id: '/_app/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AppTodoImport
      parentRoute: typeof AppImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/register/buddy-name': {
      id: '/register/buddy-name'
      path: '/buddy-name'
      fullPath: '/register/buddy-name'
      preLoaderRoute: typeof RegisterBuddyNameImport
      parentRoute: typeof RegisterImport
    }
    '/register/clothes': {
      id: '/register/clothes'
      path: '/clothes'
      fullPath: '/register/clothes'
      preLoaderRoute: typeof RegisterClothesImport
      parentRoute: typeof RegisterImport
    }
    '/register/color': {
      id: '/register/color'
      path: '/color'
      fullPath: '/register/color'
      preLoaderRoute: typeof RegisterColorImport
      parentRoute: typeof RegisterImport
    }
    '/register/hair': {
      id: '/register/hair'
      path: '/hair'
      fullPath: '/register/hair'
      preLoaderRoute: typeof RegisterHairImport
      parentRoute: typeof RegisterImport
    }
    '/register/nickname': {
      id: '/register/nickname'
      path: '/nickname'
      fullPath: '/register/nickname'
      preLoaderRoute: typeof RegisterNicknameImport
      parentRoute: typeof RegisterImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBuddyRoute: typeof AppBuddyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppTodoRoute: typeof AppTodoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBuddyRoute: AppBuddyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppTodoRoute: AppTodoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RegisterRouteChildren {
  RegisterBuddyNameRoute: typeof RegisterBuddyNameRoute
  RegisterClothesRoute: typeof RegisterClothesRoute
  RegisterColorRoute: typeof RegisterColorRoute
  RegisterHairRoute: typeof RegisterHairRoute
  RegisterNicknameRoute: typeof RegisterNicknameRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterBuddyNameRoute: RegisterBuddyNameRoute,
  RegisterClothesRoute: RegisterClothesRoute,
  RegisterColorRoute: RegisterColorRoute,
  RegisterHairRoute: RegisterHairRoute,
  RegisterNicknameRoute: RegisterNicknameRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/account': typeof AppAccountRoute
  '/buddy': typeof AppBuddyRoute
  '/dashboard': typeof AppDashboardRoute
  '/diary': typeof AppDiaryRoute
  '/todo': typeof AppTodoRoute
  '/login': typeof AuthLoginRoute
  '/register/buddy-name': typeof RegisterBuddyNameRoute
  '/register/clothes': typeof RegisterClothesRoute
  '/register/color': typeof RegisterColorRoute
  '/register/hair': typeof RegisterHairRoute
  '/register/nickname': typeof RegisterNicknameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/account': typeof AppAccountRoute
  '/buddy': typeof AppBuddyRoute
  '/dashboard': typeof AppDashboardRoute
  '/diary': typeof AppDiaryRoute
  '/todo': typeof AppTodoRoute
  '/login': typeof AuthLoginRoute
  '/register/buddy-name': typeof RegisterBuddyNameRoute
  '/register/clothes': typeof RegisterClothesRoute
  '/register/color': typeof RegisterColorRoute
  '/register/hair': typeof RegisterHairRoute
  '/register/nickname': typeof RegisterNicknameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/buddy': typeof AppBuddyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diary': typeof AppDiaryRoute
  '/_app/todo': typeof AppTodoRoute
  '/_auth/login': typeof AuthLoginRoute
  '/register/buddy-name': typeof RegisterBuddyNameRoute
  '/register/clothes': typeof RegisterClothesRoute
  '/register/color': typeof RegisterColorRoute
  '/register/hair': typeof RegisterHairRoute
  '/register/nickname': typeof RegisterNicknameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/register'
    | '/account'
    | '/buddy'
    | '/dashboard'
    | '/diary'
    | '/todo'
    | '/login'
    | '/register/buddy-name'
    | '/register/clothes'
    | '/register/color'
    | '/register/hair'
    | '/register/nickname'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/register'
    | '/account'
    | '/buddy'
    | '/dashboard'
    | '/diary'
    | '/todo'
    | '/login'
    | '/register/buddy-name'
    | '/register/clothes'
    | '/register/color'
    | '/register/hair'
    | '/register/nickname'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/register'
    | '/_app/account'
    | '/_app/buddy'
    | '/_app/dashboard'
    | '/_app/diary'
    | '/_app/todo'
    | '/_auth/login'
    | '/register/buddy-name'
    | '/register/clothes'
    | '/register/color'
    | '/register/hair'
    | '/register/nickname'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth",
        "/register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/account",
        "/_app/buddy",
        "/_app/dashboard",
        "/_app/diary",
        "/_app/todo"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/register": {
      "filePath": "register.tsx",
      "children": [
        "/register/buddy-name",
        "/register/clothes",
        "/register/color",
        "/register/hair",
        "/register/nickname"
      ]
    },
    "/_app/account": {
      "filePath": "_app/account.tsx",
      "parent": "/_app"
    },
    "/_app/buddy": {
      "filePath": "_app/buddy.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/diary": {
      "filePath": "_app/diary.tsx",
      "parent": "/_app"
    },
    "/_app/todo": {
      "filePath": "_app/todo.tsx",
      "parent": "/_app"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/register/buddy-name": {
      "filePath": "register/buddy-name.tsx",
      "parent": "/register"
    },
    "/register/clothes": {
      "filePath": "register/clothes.tsx",
      "parent": "/register"
    },
    "/register/color": {
      "filePath": "register/color.tsx",
      "parent": "/register"
    },
    "/register/hair": {
      "filePath": "register/hair.tsx",
      "parent": "/register"
    },
    "/register/nickname": {
      "filePath": "register/nickname.tsx",
      "parent": "/register"
    }
  }
}
ROUTE_MANIFEST_END */
