#
name: Change status to レビュー待ち when reviewer assigned
# This workflow runs whenever a pull request has a reviewer requested or is marked as ready for review.
on:
  pull_request:
    types:
      - review_requested
      - ready_for_review
jobs:
  track_pr:
    uses: ./.github/workflows/project_common.yml
    with:
      organization: LY-HackU-2025-team8
      project_number: 1
      status_option: "レビュー待ち"
