#
name: Change status to 作業中 when PR created
# This workflow runs whenever a pull request is opened.
on:
  pull_request:
    types:
      - opened
jobs:
  track_pr:
    uses: ./.github/workflows/project_common.yml
    with:
      organization: LY-HackU-2025-team8
      project_number: 1
      status_option: "作業中"
