name: Deploy
on:
    push:
        branches:
            - main

jobs:
    deploy-backend:
        name: Backend Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Heroku CLI
              run: |
                curl https://cli-assets.heroku.com/install.sh | sh 

            - name: Login to Heroku
              uses: akhileshns/heroku-deploy@v3.14.15
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
                heroku_email: ${{ secrets.HEROKU_EMAIL }}
                