name: Test Pull Requests
on:
  pull_request:

jobs:
  frontend-typecheck:
    name: Frontend Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: frontend_react-native
      - run: npm run typecheck
        working-directory: frontend_react-native

  frontend-format:
    name: Frontend Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: frontend_react-native
      - run: npm run format
        working-directory: frontend_react-native

  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: frontend_react-native
      - run: npm run lint
        working-directory: frontend_react-native

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: frontend_react-native
      - run: npm run prebuild
        working-directory: frontend_react-native
